name: piremit_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.1.1
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0

  # Firebase Database
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2
  firebase_database: ^10.0.7
  flutter_facebook_auth: ^4.4.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/